Iter13
rombintu/goyametricsv2 pull request #13
Opened 2024-08-16 11:03 UTC by rombintu

2024-08-24 03:34 UTC, vokinneberg requested changes
Поздравляю с первым ревью третьего спринта! 🎉 В этом спринте наше приложение стало ещё сложнее — добавился новый слой БД. 💪 Хотелось бы поделиться несколькими комментариями относительно твоего кода. 🤓

**Сильные стороны твоего PR:**

1. Код функционален и проходит тесты! 🚀
2. Ты последовательно встроил функционал в структуру существующего приложения. 👍

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Согласно условию задачи, проверку повторяемых ошибок и повторную отправку следует реализовать также и на клиенте. *Пример сценария: агент не смог с первой попытки выгрузить данные на сервер из-за временной проблемы с соединением.*
2. По условию задачи на сервере также необходимо добавить обработку повторяемых ошибок. Я этого не заметил в твоём коде.
3. Было бы отлично реализовать тесты для JSON-обработчика и для нового пакетного обработчика.
4. Согласно условию задачи, *для хранения значений gauge рекомендуется использовать тип double precision*. Похоже, это не реализовано?

2024-08-24 03:34 UTC, vokinneberg commented on Taskfile.yaml
> +  test:
Сейчас один коллега предлагает перейти на эту утилиту вместо Makeutil. Как она тебе?

2024-08-24 03:34 UTC, vokinneberg commented on cmd/agent/main.go
> +	defer cancel()
👍

2024-08-24 03:34 UTC, vokinneberg commented on cmd/server/main.go
> +	// Считаю что необязательно создавать новую переменную StorageURL (DATABASE_DSN) если есть StoragePath
Ну так решили разработчики курса, и в этом как мне кажется ест смысл, особенно если у нас есть fallback к файлу в случае, если база не сконфигурирована или недоступна. К тому же `StoragePath` не совсем корректное название для строки соединения БД.

2024-08-24 03:34 UTC, vokinneberg commented on internal/agent/agent.go
> +			if err := a.sendAllDataOnServer(a.data); err != nil {
По условию задачи проверять retriable ошибки и делать ретрай отправки следует так же и на клиенте. _Сценарии возможных ошибок:
Агент не сумел с первой попытки выгрузить данные на сервер из-за временной невозможности установить соединение с сервером._

2024-08-24 03:34 UTC, vokinneberg commented on internal/config/config.go
> +	config.StorageURL = tryLoadFromEnv("DATABASE_DSN", fromFlags.StorageURL)
Я вероятно что-то пропустил, а зачем нам на агента эти переменные окружения?

2024-08-24 03:34 UTC, vokinneberg commented on internal/config/config.go
> +	dbConfig.Host = os.Getenv("DB_HOST")
Тож не совсем понял как это используется, у нас же есть `DATABASE_DSN`?

2024-08-24 03:34 UTC, vokinneberg commented on internal/server/handlers.go
> +		logger.Log.Error(err.Error(), zap.String("type", mtype), zap.String("id/name", mname))
Если каждый раз логируется `mtype` и ` mname`  может быть удобно создать логгер с этими значениями и не передавать их при каждой записи в лог:
 ```go
logger = logger.With(zap.String("mtype", mtype), zap.String("mname", mname))
```

2024-08-24 03:34 UTC, vokinneberg commented on internal/server/handlers.go
> +		zap.Any("delta", metric.Delta),
Вообще, если известен тип переменной лучше избегать использования `zap.Any()`, так как там внутри скорее всего используется рефлексия и это может быть н очень оптимально.

2024-08-24 03:34 UTC, vokinneberg commented on internal/server/handlers.go
> +	err := errors.New("delta or value must be not null")
Я понимаю, что хочется тут сделать оптимизацию, но мне кажется во-первых эта ошибка можео никогда не пригодится, я во-вторых можно просто по месту вызвать `errors.New("delta must be not null")` или `errors.New("value must be not null")` - это будет более информативно, так как понятно в чем же все-таки проблема и не сильно многословней.

2024-08-24 03:34 UTC, vokinneberg commented on internal/server/server.go
> +func (s *Server) RetryConfigureStorage(interval time.Duration) error {
Этот метод нам точно нужен?

2024-08-24 03:34 UTC, vokinneberg commented on internal/storage/pgx_driver.go
> +func (d *pgxDriver) updateAny(ctx context.Context, m AnyMetrics, mtype string) error {
Не хочу занудствовать по поводу английского языка, но any буквально означает любой, что прямо противоположно по смыслу тому, что делает код.

```suggestion
func (d *pgxDriver) updateAll(ctx context.Context, m AnyMetrics, mtype string) error {
```

2024-08-24 03:34 UTC, vokinneberg commented on internal/storage/pgx_driver.go
> +	CREATE TABLE IF NOT EXISTS metrics (
По условию задачи _Для хранения значений gauge рекомендуется использовать тип double precision._ По-поему это не реализовано?

2024-08-24 03:34 UTC, vokinneberg commented on internal/storage/pgx_driver.go
> +	tx, err := d.conn.Begin(ctx)
👍 за использовании  транзакции.

2024-08-24 03:34 UTC, vokinneberg commented on internal/storage/create_table_metrics.sql
> +CREATE DATABASE metrics;
Вообще нам нужен это файл?

2024-08-24 10:26 UTC, rombintu commented on Taskfile.yaml
> +  test:
Я до этого пользовался обычным make (Makefile), перешел с радостью, очень гибкая настройка, много функциональности, хорошая документация. Попробовать стоит

2024-08-24 10:29 UTC, rombintu commented on cmd/server/main.go
> +	// Считаю что необязательно создавать новую переменную StorageURL (DATABASE_DSN) если есть StoragePath
По мне логичнее чтобы был всего один параметр, который управляет сразу несколькими логиками. Я работаю в облаке и по опыту могу сказать, что те инструменты, где разработчик решил использовать под каждый чих какой то параметр - являются очень перегруженными по документации и пониманию конченого пользователя. С точки зрения разработчика может быть это и удобно, не спорю

2024-08-24 10:32 UTC, rombintu commented on cmd/server/main.go
> +	// Считаю что необязательно создавать новую переменную StorageURL (DATABASE_DSN) если есть StoragePath
Но мое решение одновременно и покрывает ТЗ и мои какие то "принципы", просто дополнительная проверка, которая особо не влияет на производительность, но тот кто будет разворачивать проект, может без документации интуитивно все настроить, благодаря этому решению. Если тесты проходят, мне это переделывать?

2024-08-24 10:41 UTC, rombintu commented on internal/agent/agent.go
> +			if err := a.sendAllDataOnServer(a.data); err != nil {
Такс, я это реализовал в 13 инкременте, но из за "ребейзов" все куда то пропало. Ну еще сама реализация была в самом запуске агента, а не при уже отправке данных, по мне лучше сразу проверить доступность до сервера, чем этим заниматься после затрат ресурсов

2024-08-24 10:44 UTC, rombintu commented on internal/config/config.go
> +	config.StorageURL = tryLoadFromEnv("DATABASE_DSN", fromFlags.StorageURL)
Это все происходит в функции LoadServerConfig(), а сама функция и все что принадлежит Агенту - находятся в одно файле, чтобы не перегружать структуру

2024-08-24 10:46 UTC, rombintu commented on internal/server/server.go
> +func (s *Server) RetryConfigureStorage(interval time.Duration) error {
Это видимо была какая то TODO, но реализация потерялась из за мерджа веток, видимо что то не так сделал, попытался через Веб версию все провернуть :\

2024-08-24 10:49 UTC, rombintu commented on internal/storage/pgx_driver.go
> +func (d *pgxDriver) updateAny(ctx context.Context, m AnyMetrics, mtype string) error {
Возможно, но эта функция вызывается в функции UpdateAll(), если переименовать то теряется понимание что делает функция, а при просмотре всего файла а не конкретного кусочка все становиться понятно

2024-08-24 10:54 UTC, rombintu commented on internal/storage/pgx_driver.go
> +	CREATE TABLE IF NOT EXISTS metrics (
Из за надобности поступающим данным быть универсальными и для облегчения реализации я решил создать одну табличку, с универсальными метриками, которые отличаются только типом, а их значение я перевожу в string. К тому же слово "рекомендуется" не обязывает делать это. Мне будет сложно сейчас в короткий срок переделать основную логику с хранением данных, так что я скорее всего оставлю это как есть. Тесты все проходят, все работает как нужно)

2024-08-24 10:56 UTC, rombintu commented on internal/storage/create_table_metrics.sql
> +CREATE DATABASE metrics;
Нужен мне для локального развертывания БД, добавлю в гитигнор

2024-08-24 11:13 UTC, rombintu commented on internal/config/config.go
> +	dbConfig.Host = os.Getenv("DB_HOST")
Дополнительный подсос из env, для упрощения настройки, можно их не указывать, можно указать DATABASE_DSN, можно их указать и DATABASE_DSN одновременно, будет читаться по приоритету

2024-08-24 11:24 UTC, rombintu commented on internal/server/handlers.go
> +		zap.Any("delta", metric.Delta),
Да, но в данном случае у нас указатели, их нельзя использовать как Int64 или Float64. Я хотел убрать вообще это логирование, но оно мне необходимо пока приложение не покрыто тестами, для понятия процесса без дебага

2024-08-24 12:23 UTC, rombintu commented on internal/config/config.go
> +	config.StorageURL = tryLoadFromEnv("DATABASE_DSN", fromFlags.StorageURL)
в 14 инкременте я пришел к тому, что лучше разделить файлы Agent & Server

2024-08-28 02:49 UTC, vokinneberg commented on cmd/server/main.go
> +	// Считаю что необязательно создавать новую переменную StorageURL (DATABASE_DSN) если есть StoragePath
Нет, не нужно переделывать. Для меня достаточно такого обоснования. 👍

2024-08-28 02:50 UTC, vokinneberg commented on internal/config/config.go
> +	dbConfig.Host = os.Getenv("DB_HOST")
По мне так немного оверхед, но не критично.

2024-08-28 02:51 UTC, vokinneberg commented on internal/server/handlers.go
> +		zap.Any("delta", metric.Delta),
ОК, но я предупредил 👻

2024-08-28 02:59 UTC, vokinneberg approved these changes
Поздравляю с завершением третьего спринта. Отличная работа! 🚀

От себя отмечу всё же одно обстоятельство — ты часто мотивируешь свои решения исходя из того, что "тесты проходят". Всё же тесты написаны таким образом, чтобы проверить выполнение минимальных требований, и, как ты успел заметить, могут быть не полными даже по отношению к постановке задачи. Возможно, в рабочем проекте это было бы валидным обоснованием, но так как мы учимся, для нас иногда пойти *кривым* путём значит получить новые знания, которые пригодятся нам в будущем. 😊

2024-08-28 09:26 UTC, merged