Iter23
rombintu/goyametricsv2 pull request #21
Opened 2024-11-26 15:12 UTC by rombintu

2024-11-28 03:03 UTC, vokinneberg approved these changes
Поздравляю с первым ревью девятого спринта! 🎉 Продолжаем улучшать наше приложение и покрывать его тестами! ⚡ По традиции хочу оставить несколько замечаний по улучшению твоего кода. 🤓

**Сильные стороны твоего PR:**

1. Ты реализовал функционал, требующийся по ТЗ 👍
2. Ты улучшил покрытие кода тестами 🙌

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Было бы здорово покрыть приложение тестами, которые проверяют корректную очередность загрузки конфигурации, а также то, что корректно загружается конфигурация по умолчанию в случае отсутствия файла.
2. Общее покрытие ниже, чем требуется по условию задачи.
3. Не стоит игнорировать ошибки, стоит их обработать и либо записать в лог, либо прервать работу приложения в зависимости от бизнес-логики загрузки.

2024-11-28 03:03 UTC, vokinneberg commented on cmd/server/main.go
> +	if conf.PrivateKeyFile != "" {
Не совсем понятно, для чего вводить переменную `SecureMode`, если проверка все равно сводится к проверке `conf.PrivateKeyFile != ""`.

2024-11-28 03:03 UTC, vokinneberg commented on internal/agent/agent.go
> +			logger.Log.Error(err.Error())
Не совсем понятно почему пишется две записи в лог на уровне Warn и Error, мне кажется будет достаточно одной записи: 
```suggestion
			logger.Log.Error("Failed to load public key. SecureMode set False", zap.Error(err), zap.String("file", a.publicKeyFile))
```

2024-11-28 03:03 UTC, vokinneberg commented on internal/config/agent.go
> +		fromFile, _ = loadAgentConfigFromFile(config.ConfigPathFile)
Не стоит игнорировать ошибку, стоит ее обработать и либо записать в лог, либо прервать работу проложения в зависимости от бизнес-логики загрузки.

2024-11-28 03:04 UTC, vokinneberg requested changes
Поздравляю с первым ревью девятого спринта! 🎉 Продолжаем улучшать наше приложение и покрывать его тестами! ⚡ По традиции хочу оставить несколько замечаний по улучшению твоего кода. 🤓

**Сильные стороны твоего PR:**

1. Ты реализовал функционал, требующийся по ТЗ 👍
2. Ты улучшил покрытие кода тестами 🙌

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Было бы здорово покрыть приложение тестами, которые проверяют корректную очередность загрузки конфигурации, а также то, что корректно загружается конфигурация по умолчанию в случае отсутствия файла.
2. Общее покрытие ниже, чем требуется по условию задачи.
3. Не стоит игнорировать ошибки, стоит их обработать и либо записать в лог, либо прервать работу приложения в зависимости от бизнес-логики загрузки.

2024-11-28 11:28 UTC, rombintu commented on cmd/server/main.go
> +	if conf.PrivateKeyFile != "" {
Для работы в булевым значением. Логически, установка ключа не означает что используется безопасный режим, потому что для тз нужно указать только путь до ключа. Времени не было довести до ума, пока что делаю все с заделом на будущее

2024-11-28 11:31 UTC, rombintu commented on internal/config/agent.go
> +		fromFile, _ = loadAgentConfigFromFile(config.ConfigPathFile)
сначала загружается конфиг а потом логгер. Я подумал раз файл самый неприоритетный, то и сообщение о том, что там что то не загрузилось - смысла мало. Но я попробую что нибудь придумать

2024-11-30 03:13 UTC, vokinneberg approved these changes
Поздравляю с успешным ревью девятого спринта! 🎉 Ты значительно улучшил структуру тестов и у твоего приложения хороший процент покрытия. Так держать! 🙌

2024-12-01 09:33 UTC, merged